### ISSUE TITLE
Icon/logo replacement

### ISSUE THREAD

**Issue by ItsRogueRen** [SchildiChat/schildichat-graphics#1]
The SchildiChat icon is very off-putting to many people I've attempted to convert to use as an alternative to Discord. As such, I've made a mock up of a more modern looking icon that would appeal to more people while still keeping the turtle theme. 

![schildichat](https://user-images.githubusercontent.com/75085610/196576457-7d264182-f26e-417b-8c2f-31d12275c201.png)

**Comment by SpiritCroc** [comment]
Thanks for your suggestion. This icon looks too generic to me.

Note there has been some discussion about icons, which you might want to read back to get some ideas about our requirements: https://github.com/SchildiChat/schildichat-graphics/issues/2
The above linked issue was on the Android repo, but I figured this repo makes more sense so I moved it here too, I'll close this one as duplicate.
